### ISSUE TITLE
Trial: no sensible output

### ISSUE THREAD

**Issue by cogumbreiro** [capergroup/bayou#142]
The following trial is to concatenate a list of strings into one string, using a StringBuffer.
```
tool_files/floodgage/trials/string_buffer_concat/trials.jar
```
However, I'm not getting any meaningful outputs.

**Comment by vijay-murali** [comment]
This is because the trial is cutting across two different top-level packages: java.util (Iterator) and java.lang (StringBuffer). I would suggest avoiding this for now, and creating trials that only use classes within a single package. This is one of the current limitations of Bayou, but I don't think we will address it in this release.

**Comment by cogumbreiro** [comment]
Will do.

**Comment by vijay-murali** [comment]
Closing the thread. Reopen if you have further questions/issues.
